/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Service Tracker API
 * An API to track vehicle maintenance records.
 * OpenAPI spec version: 0.0.1
 */
import * as zod from 'zod';

/**
 * @summary Retrieve a list of vehicles
 */
export const listVehiclesResponseYearMin = 1900;
export const listVehiclesResponseYearMax = 2026;



export const listVehiclesResponseItem = zod.object({
  "id": zod.string(),
  "make": zod.string(),
  "model": zod.string(),
  "year": zod.number().min(listVehiclesResponseYearMin).max(listVehiclesResponseYearMax)
})
export const listVehiclesResponse = zod.array(listVehiclesResponseItem)


/**
 * @summary Add a new vehicle
 */
export const createVehicleBodyYearMin = 1900;
export const createVehicleBodyYearMax = 2026;



export const createVehicleBody = zod.object({
  "make": zod.string(),
  "model": zod.string(),
  "year": zod.number().min(createVehicleBodyYearMin).max(createVehicleBodyYearMax)
})


/**
 * @summary Retrieve a vehicle by ID
 */
export const getVehicleParams = zod.object({
  "vehicleId": zod.string()
})

export const getVehicleResponseYearMin = 1900;
export const getVehicleResponseYearMax = 2026;



export const getVehicleResponse = zod.object({
  "id": zod.string(),
  "make": zod.string(),
  "model": zod.string(),
  "year": zod.number().min(getVehicleResponseYearMin).max(getVehicleResponseYearMax)
})


/**
 * @summary Update an existing vehicle
 */
export const updateVehicleParams = zod.object({
  "vehicleId": zod.string()
})

export const updateVehicleBodyYearMin = 1900;
export const updateVehicleBodyYearMax = 2026;



export const updateVehicleBody = zod.object({
  "make": zod.string(),
  "model": zod.string(),
  "year": zod.number().min(updateVehicleBodyYearMin).max(updateVehicleBodyYearMax)
})


/**
 * @summary Delete a vehicle
 */
export const deleteVehicleParams = zod.object({
  "vehicleId": zod.string()
})


/**
 * @summary Retrieve images for a vehicle
 */
export const getVehicleImagesParams = zod.object({
  "vehicleId": zod.string()
})

export const getVehicleImagesResponseItem = zod.object({
  "id": zod.number().optional(),
  "filename": zod.string()
})
export const getVehicleImagesResponse = zod.array(getVehicleImagesResponseItem)


/**
 * @summary Retrieve maintenance records for a vehicle
 */
export const listMaintenanceRecordsParams = zod.object({
  "vehicleId": zod.string()
})

export const listMaintenanceRecordsResponseMileageMin = 0;



export const listMaintenanceRecordsResponseItem = zod.object({
  "id": zod.string().optional(),
  "cost": zod.string().optional().describe('Cost of the service.'),
  "date": zod.iso.date(),
  "description": zod.string(),
  "mileage": zod.number().min(listMaintenanceRecordsResponseMileageMin),
  "notes": zod.string().optional().describe('Optional notes.')
})
export const listMaintenanceRecordsResponse = zod.array(listMaintenanceRecordsResponseItem)


/**
 * @summary Add a maintenance record for a vehicle
 */
export const createMaintenanceRecordParams = zod.object({
  "vehicleId": zod.string()
})

export const createMaintenanceRecordBodyMileageMin = 0;



export const createMaintenanceRecordBody = zod.object({
  "cost": zod.string().optional().describe('Cost of the service.'),
  "date": zod.iso.date(),
  "description": zod.string(),
  "mileage": zod.number().min(createMaintenanceRecordBodyMileageMin),
  "notes": zod.string().optional().describe('Optional notes.')
})


/**
 * @summary Retrieve a specific maintenance record
 */
export const getMaintenanceRecordParams = zod.object({
  "vehicleId": zod.string(),
  "recordId": zod.string()
})

export const getMaintenanceRecordResponseMileageMin = 0;



export const getMaintenanceRecordResponse = zod.object({
  "id": zod.string().optional(),
  "cost": zod.string().optional().describe('Cost of the service.'),
  "date": zod.iso.date(),
  "description": zod.string(),
  "mileage": zod.number().min(getMaintenanceRecordResponseMileageMin),
  "notes": zod.string().optional().describe('Optional notes.')
})


/**
 * @summary Update an existing maintenance record
 */
export const updateMaintenanceRecordParams = zod.object({
  "vehicleId": zod.string(),
  "recordId": zod.string()
})

export const updateMaintenanceRecordBodyMileageMin = 0;



export const updateMaintenanceRecordBody = zod.object({
  "cost": zod.string().optional().describe('Cost of the service.'),
  "date": zod.iso.date(),
  "description": zod.string(),
  "mileage": zod.number().min(updateMaintenanceRecordBodyMileageMin),
  "notes": zod.string().optional().describe('Optional notes.')
})


/**
 * @summary Delete a maintenance record
 */
export const deleteMaintenanceRecordParams = zod.object({
  "vehicleId": zod.string(),
  "recordId": zod.string()
})
