/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Service Tracker API
 * An API to track vehicle maintenance records.
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customFetch } from './custom-fetch';
import type { ErrorType } from './custom-fetch';

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

export interface MaintenanceRecord {
  readonly id?: string;
  /** Cost of the service. */
  cost?: string;
  date: string;
  description: string;
  /** @minimum 0 */
  mileage: number;
  /** Optional notes. */
  notes?: string;
}

export interface Vehicle {
  readonly id?: string;
  make: string;
  model: string;
  /**
   * @minimum 1900
   * @maximum 2025
   */
  year: number;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Retrieve a list of vehicles
 */
export const getListVehiclesUrl = () => {


  

  return `http://localhost:8080/vehicles`
}

export const listVehicles = async ( options?: RequestInit): Promise<Vehicle[]> => {
  
  return customFetch<Vehicle[]>(getListVehiclesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListVehiclesQueryKey = () => {
    return [
    `http://localhost:8080/vehicles`
    ] as const;
    }

    
export const getListVehiclesQueryOptions = <TData = Awaited<ReturnType<typeof listVehicles>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVehicles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListVehiclesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listVehicles>>> = ({ signal }) => listVehicles({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listVehicles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListVehiclesQueryResult = NonNullable<Awaited<ReturnType<typeof listVehicles>>>
export type ListVehiclesQueryError = ErrorType<unknown>


export function useListVehicles<TData = Awaited<ReturnType<typeof listVehicles>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVehicles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVehicles>>,
          TError,
          Awaited<ReturnType<typeof listVehicles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVehicles<TData = Awaited<ReturnType<typeof listVehicles>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVehicles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listVehicles>>,
          TError,
          Awaited<ReturnType<typeof listVehicles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListVehicles<TData = Awaited<ReturnType<typeof listVehicles>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVehicles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieve a list of vehicles
 */

export function useListVehicles<TData = Awaited<ReturnType<typeof listVehicles>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listVehicles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListVehiclesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Add a new vehicle
 */
export const getCreateVehicleUrl = () => {


  

  return `http://localhost:8080/vehicles`
}

export const createVehicle = async (vehicle: NonReadonly<Vehicle>, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getCreateVehicleUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      vehicle,)
  }
);}




export const getCreateVehicleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVehicle>>, TError,{data: NonReadonly<Vehicle>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createVehicle>>, TError,{data: NonReadonly<Vehicle>}, TContext> => {

const mutationKey = ['createVehicle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createVehicle>>, {data: NonReadonly<Vehicle>}> = (props) => {
          const {data} = props ?? {};

          return  createVehicle(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateVehicleMutationResult = NonNullable<Awaited<ReturnType<typeof createVehicle>>>
    export type CreateVehicleMutationBody = NonReadonly<Vehicle>
    export type CreateVehicleMutationError = ErrorType<unknown>

    /**
 * @summary Add a new vehicle
 */
export const useCreateVehicle = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createVehicle>>, TError,{data: NonReadonly<Vehicle>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createVehicle>>,
        TError,
        {data: NonReadonly<Vehicle>},
        TContext
      > => {

      const mutationOptions = getCreateVehicleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Retrieve a vehicle by ID
 */
export const getGetVehicleUrl = (vehicleId: string,) => {


  

  return `http://localhost:8080/vehicles/${vehicleId}`
}

export const getVehicle = async (vehicleId: string, options?: RequestInit): Promise<Vehicle> => {
  
  return customFetch<Vehicle>(getGetVehicleUrl(vehicleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetVehicleQueryKey = (vehicleId?: string,) => {
    return [
    `http://localhost:8080/vehicles/${vehicleId}`
    ] as const;
    }

    
export const getGetVehicleQueryOptions = <TData = Awaited<ReturnType<typeof getVehicle>>, TError = ErrorType<void>>(vehicleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVehicle>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVehicleQueryKey(vehicleId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVehicle>>> = ({ signal }) => getVehicle(vehicleId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(vehicleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVehicle>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVehicleQueryResult = NonNullable<Awaited<ReturnType<typeof getVehicle>>>
export type GetVehicleQueryError = ErrorType<void>


export function useGetVehicle<TData = Awaited<ReturnType<typeof getVehicle>>, TError = ErrorType<void>>(
 vehicleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVehicle>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVehicle>>,
          TError,
          Awaited<ReturnType<typeof getVehicle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVehicle<TData = Awaited<ReturnType<typeof getVehicle>>, TError = ErrorType<void>>(
 vehicleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVehicle>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVehicle>>,
          TError,
          Awaited<ReturnType<typeof getVehicle>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVehicle<TData = Awaited<ReturnType<typeof getVehicle>>, TError = ErrorType<void>>(
 vehicleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVehicle>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieve a vehicle by ID
 */

export function useGetVehicle<TData = Awaited<ReturnType<typeof getVehicle>>, TError = ErrorType<void>>(
 vehicleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVehicle>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVehicleQueryOptions(vehicleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update an existing vehicle
 */
export const getUpdateVehicleUrl = (vehicleId: string,) => {


  

  return `http://localhost:8080/vehicles/${vehicleId}`
}

export const updateVehicle = async (vehicleId: string,
    vehicle: NonReadonly<Vehicle>, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getUpdateVehicleUrl(vehicleId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      vehicle,)
  }
);}




export const getUpdateVehicleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVehicle>>, TError,{vehicleId: string;data: NonReadonly<Vehicle>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateVehicle>>, TError,{vehicleId: string;data: NonReadonly<Vehicle>}, TContext> => {

const mutationKey = ['updateVehicle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateVehicle>>, {vehicleId: string;data: NonReadonly<Vehicle>}> = (props) => {
          const {vehicleId,data} = props ?? {};

          return  updateVehicle(vehicleId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateVehicleMutationResult = NonNullable<Awaited<ReturnType<typeof updateVehicle>>>
    export type UpdateVehicleMutationBody = NonReadonly<Vehicle>
    export type UpdateVehicleMutationError = ErrorType<unknown>

    /**
 * @summary Update an existing vehicle
 */
export const useUpdateVehicle = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateVehicle>>, TError,{vehicleId: string;data: NonReadonly<Vehicle>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateVehicle>>,
        TError,
        {vehicleId: string;data: NonReadonly<Vehicle>},
        TContext
      > => {

      const mutationOptions = getUpdateVehicleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete a vehicle
 */
export const getDeleteVehicleUrl = (vehicleId: string,) => {


  

  return `http://localhost:8080/vehicles/${vehicleId}`
}

export const deleteVehicle = async (vehicleId: string, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getDeleteVehicleUrl(vehicleId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteVehicleMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVehicle>>, TError,{vehicleId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteVehicle>>, TError,{vehicleId: string}, TContext> => {

const mutationKey = ['deleteVehicle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteVehicle>>, {vehicleId: string}> = (props) => {
          const {vehicleId} = props ?? {};

          return  deleteVehicle(vehicleId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteVehicleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteVehicle>>>
    
    export type DeleteVehicleMutationError = ErrorType<unknown>

    /**
 * @summary Delete a vehicle
 */
export const useDeleteVehicle = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteVehicle>>, TError,{vehicleId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteVehicle>>,
        TError,
        {vehicleId: string},
        TContext
      > => {

      const mutationOptions = getDeleteVehicleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Retrieve maintenance records for a vehicle
 */
export const getListMaintenanceRecordsUrl = (vehicleId: string,) => {


  

  return `http://localhost:8080/vehicles/${vehicleId}/maintenance`
}

export const listMaintenanceRecords = async (vehicleId: string, options?: RequestInit): Promise<MaintenanceRecord[]> => {
  
  return customFetch<MaintenanceRecord[]>(getListMaintenanceRecordsUrl(vehicleId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListMaintenanceRecordsQueryKey = (vehicleId?: string,) => {
    return [
    `http://localhost:8080/vehicles/${vehicleId}/maintenance`
    ] as const;
    }

    
export const getListMaintenanceRecordsQueryOptions = <TData = Awaited<ReturnType<typeof listMaintenanceRecords>>, TError = ErrorType<unknown>>(vehicleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMaintenanceRecords>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMaintenanceRecordsQueryKey(vehicleId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMaintenanceRecords>>> = ({ signal }) => listMaintenanceRecords(vehicleId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(vehicleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMaintenanceRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMaintenanceRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof listMaintenanceRecords>>>
export type ListMaintenanceRecordsQueryError = ErrorType<unknown>


export function useListMaintenanceRecords<TData = Awaited<ReturnType<typeof listMaintenanceRecords>>, TError = ErrorType<unknown>>(
 vehicleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMaintenanceRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMaintenanceRecords>>,
          TError,
          Awaited<ReturnType<typeof listMaintenanceRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMaintenanceRecords<TData = Awaited<ReturnType<typeof listMaintenanceRecords>>, TError = ErrorType<unknown>>(
 vehicleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMaintenanceRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMaintenanceRecords>>,
          TError,
          Awaited<ReturnType<typeof listMaintenanceRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMaintenanceRecords<TData = Awaited<ReturnType<typeof listMaintenanceRecords>>, TError = ErrorType<unknown>>(
 vehicleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMaintenanceRecords>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieve maintenance records for a vehicle
 */

export function useListMaintenanceRecords<TData = Awaited<ReturnType<typeof listMaintenanceRecords>>, TError = ErrorType<unknown>>(
 vehicleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMaintenanceRecords>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMaintenanceRecordsQueryOptions(vehicleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Add a maintenance record for a vehicle
 */
export const getCreateMaintenanceRecordUrl = (vehicleId: string,) => {


  

  return `http://localhost:8080/vehicles/${vehicleId}/maintenance`
}

export const createMaintenanceRecord = async (vehicleId: string,
    maintenanceRecord: NonReadonly<MaintenanceRecord>, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getCreateMaintenanceRecordUrl(vehicleId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      maintenanceRecord,)
  }
);}




export const getCreateMaintenanceRecordMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMaintenanceRecord>>, TError,{vehicleId: string;data: NonReadonly<MaintenanceRecord>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createMaintenanceRecord>>, TError,{vehicleId: string;data: NonReadonly<MaintenanceRecord>}, TContext> => {

const mutationKey = ['createMaintenanceRecord'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMaintenanceRecord>>, {vehicleId: string;data: NonReadonly<MaintenanceRecord>}> = (props) => {
          const {vehicleId,data} = props ?? {};

          return  createMaintenanceRecord(vehicleId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMaintenanceRecordMutationResult = NonNullable<Awaited<ReturnType<typeof createMaintenanceRecord>>>
    export type CreateMaintenanceRecordMutationBody = NonReadonly<MaintenanceRecord>
    export type CreateMaintenanceRecordMutationError = ErrorType<unknown>

    /**
 * @summary Add a maintenance record for a vehicle
 */
export const useCreateMaintenanceRecord = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMaintenanceRecord>>, TError,{vehicleId: string;data: NonReadonly<MaintenanceRecord>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMaintenanceRecord>>,
        TError,
        {vehicleId: string;data: NonReadonly<MaintenanceRecord>},
        TContext
      > => {

      const mutationOptions = getCreateMaintenanceRecordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Retrieve a specific maintenance record
 */
export const getGetMaintenanceRecordUrl = (vehicleId: string,
    recordId: string,) => {


  

  return `http://localhost:8080/vehicles/${vehicleId}/maintenance/${recordId}`
}

export const getMaintenanceRecord = async (vehicleId: string,
    recordId: string, options?: RequestInit): Promise<MaintenanceRecord> => {
  
  return customFetch<MaintenanceRecord>(getGetMaintenanceRecordUrl(vehicleId,recordId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMaintenanceRecordQueryKey = (vehicleId?: string,
    recordId?: string,) => {
    return [
    `http://localhost:8080/vehicles/${vehicleId}/maintenance/${recordId}`
    ] as const;
    }

    
export const getGetMaintenanceRecordQueryOptions = <TData = Awaited<ReturnType<typeof getMaintenanceRecord>>, TError = ErrorType<void>>(vehicleId: string,
    recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaintenanceRecord>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMaintenanceRecordQueryKey(vehicleId,recordId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMaintenanceRecord>>> = ({ signal }) => getMaintenanceRecord(vehicleId,recordId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(vehicleId && recordId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMaintenanceRecord>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMaintenanceRecordQueryResult = NonNullable<Awaited<ReturnType<typeof getMaintenanceRecord>>>
export type GetMaintenanceRecordQueryError = ErrorType<void>


export function useGetMaintenanceRecord<TData = Awaited<ReturnType<typeof getMaintenanceRecord>>, TError = ErrorType<void>>(
 vehicleId: string,
    recordId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaintenanceRecord>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMaintenanceRecord>>,
          TError,
          Awaited<ReturnType<typeof getMaintenanceRecord>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMaintenanceRecord<TData = Awaited<ReturnType<typeof getMaintenanceRecord>>, TError = ErrorType<void>>(
 vehicleId: string,
    recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaintenanceRecord>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMaintenanceRecord>>,
          TError,
          Awaited<ReturnType<typeof getMaintenanceRecord>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMaintenanceRecord<TData = Awaited<ReturnType<typeof getMaintenanceRecord>>, TError = ErrorType<void>>(
 vehicleId: string,
    recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaintenanceRecord>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieve a specific maintenance record
 */

export function useGetMaintenanceRecord<TData = Awaited<ReturnType<typeof getMaintenanceRecord>>, TError = ErrorType<void>>(
 vehicleId: string,
    recordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaintenanceRecord>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMaintenanceRecordQueryOptions(vehicleId,recordId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update an existing maintenance record
 */
export const getUpdateMaintenanceRecordUrl = (vehicleId: string,
    recordId: string,) => {


  

  return `http://localhost:8080/vehicles/${vehicleId}/maintenance/${recordId}`
}

export const updateMaintenanceRecord = async (vehicleId: string,
    recordId: string,
    maintenanceRecord: NonReadonly<MaintenanceRecord>, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getUpdateMaintenanceRecordUrl(vehicleId,recordId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      maintenanceRecord,)
  }
);}




export const getUpdateMaintenanceRecordMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMaintenanceRecord>>, TError,{vehicleId: string;recordId: string;data: NonReadonly<MaintenanceRecord>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMaintenanceRecord>>, TError,{vehicleId: string;recordId: string;data: NonReadonly<MaintenanceRecord>}, TContext> => {

const mutationKey = ['updateMaintenanceRecord'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMaintenanceRecord>>, {vehicleId: string;recordId: string;data: NonReadonly<MaintenanceRecord>}> = (props) => {
          const {vehicleId,recordId,data} = props ?? {};

          return  updateMaintenanceRecord(vehicleId,recordId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMaintenanceRecordMutationResult = NonNullable<Awaited<ReturnType<typeof updateMaintenanceRecord>>>
    export type UpdateMaintenanceRecordMutationBody = NonReadonly<MaintenanceRecord>
    export type UpdateMaintenanceRecordMutationError = ErrorType<unknown>

    /**
 * @summary Update an existing maintenance record
 */
export const useUpdateMaintenanceRecord = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMaintenanceRecord>>, TError,{vehicleId: string;recordId: string;data: NonReadonly<MaintenanceRecord>}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMaintenanceRecord>>,
        TError,
        {vehicleId: string;recordId: string;data: NonReadonly<MaintenanceRecord>},
        TContext
      > => {

      const mutationOptions = getUpdateMaintenanceRecordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete a maintenance record
 */
export const getDeleteMaintenanceRecordUrl = (vehicleId: string,
    recordId: string,) => {


  

  return `http://localhost:8080/vehicles/${vehicleId}/maintenance/${recordId}`
}

export const deleteMaintenanceRecord = async (vehicleId: string,
    recordId: string, options?: RequestInit): Promise<void> => {
  
  return customFetch<void>(getDeleteMaintenanceRecordUrl(vehicleId,recordId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteMaintenanceRecordMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMaintenanceRecord>>, TError,{vehicleId: string;recordId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMaintenanceRecord>>, TError,{vehicleId: string;recordId: string}, TContext> => {

const mutationKey = ['deleteMaintenanceRecord'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMaintenanceRecord>>, {vehicleId: string;recordId: string}> = (props) => {
          const {vehicleId,recordId} = props ?? {};

          return  deleteMaintenanceRecord(vehicleId,recordId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMaintenanceRecordMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMaintenanceRecord>>>
    
    export type DeleteMaintenanceRecordMutationError = ErrorType<unknown>

    /**
 * @summary Delete a maintenance record
 */
export const useDeleteMaintenanceRecord = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMaintenanceRecord>>, TError,{vehicleId: string;recordId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMaintenanceRecord>>,
        TError,
        {vehicleId: string;recordId: string},
        TContext
      > => {

      const mutationOptions = getDeleteMaintenanceRecordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
