/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Service Tracker API
 * An API to track vehicle maintenance records.
 * OpenAPI spec version: 0.0.1
 */
import * as zod from 'zod';

/**
 * @summary Retrieve a list of vehicles
 */
export const listVehiclesResponseYearMin = 1900;
export const listVehiclesResponseYearMax = 2026;



export const ListVehiclesResponseItem = zod.object({
  "id": zod.string(),
  "make": zod.string(),
  "model": zod.string(),
  "year": zod.number().min(listVehiclesResponseYearMin).max(listVehiclesResponseYearMax)
})
export const ListVehiclesResponse = zod.array(ListVehiclesResponseItem)


/**
 * @summary Add a new vehicle
 */
export const createVehicleBodyYearMin = 1900;
export const createVehicleBodyYearMax = 2026;



export const CreateVehicleBody = zod.object({
  "make": zod.string(),
  "model": zod.string(),
  "year": zod.number().min(createVehicleBodyYearMin).max(createVehicleBodyYearMax)
})


/**
 * @summary Retrieve a vehicle by ID
 */
export const GetVehicleParams = zod.object({
  "vehicleId": zod.string()
})

export const getVehicleResponseYearMin = 1900;
export const getVehicleResponseYearMax = 2026;



export const GetVehicleResponse = zod.object({
  "id": zod.string(),
  "make": zod.string(),
  "model": zod.string(),
  "year": zod.number().min(getVehicleResponseYearMin).max(getVehicleResponseYearMax)
})


/**
 * @summary Update an existing vehicle
 */
export const UpdateVehicleParams = zod.object({
  "vehicleId": zod.string()
})

export const updateVehicleBodyYearMin = 1900;
export const updateVehicleBodyYearMax = 2026;



export const UpdateVehicleBody = zod.object({
  "make": zod.string(),
  "model": zod.string(),
  "year": zod.number().min(updateVehicleBodyYearMin).max(updateVehicleBodyYearMax)
})


/**
 * @summary Delete a vehicle
 */
export const DeleteVehicleParams = zod.object({
  "vehicleId": zod.string()
})


/**
 * @summary Retrieve images for a vehicle
 */
export const GetVehicleImagesParams = zod.object({
  "vehicleId": zod.string()
})

export const GetVehicleImagesResponseItem = zod.object({
  "id": zod.number().optional(),
  "filename": zod.string()
})
export const GetVehicleImagesResponse = zod.array(GetVehicleImagesResponseItem)


/**
 * @summary Trigger image download for a vehicle
 */
export const FetchVehicleImagesParams = zod.object({
  "vehicleId": zod.string()
})


/**
 * @summary Retrieve maintenance records for a vehicle
 */
export const ListMaintenanceRecordsParams = zod.object({
  "vehicleId": zod.string()
})

export const listMaintenanceRecordsResponseMileageMin = 0;



export const ListMaintenanceRecordsResponseItem = zod.object({
  "id": zod.string().optional(),
  "cost": zod.string().optional().describe('Cost of the service.'),
  "date": zod.iso.date(),
  "description": zod.string(),
  "mileage": zod.number().min(listMaintenanceRecordsResponseMileageMin),
  "notes": zod.string().optional().describe('Optional notes.')
})
export const ListMaintenanceRecordsResponse = zod.array(ListMaintenanceRecordsResponseItem)


/**
 * @summary Add a maintenance record for a vehicle
 */
export const CreateMaintenanceRecordParams = zod.object({
  "vehicleId": zod.string()
})

export const createMaintenanceRecordBodyMileageMin = 0;



export const CreateMaintenanceRecordBody = zod.object({
  "cost": zod.string().optional().describe('Cost of the service.'),
  "date": zod.iso.date(),
  "description": zod.string(),
  "mileage": zod.number().min(createMaintenanceRecordBodyMileageMin),
  "notes": zod.string().optional().describe('Optional notes.')
})


/**
 * @summary Retrieve a specific maintenance record
 */
export const GetMaintenanceRecordParams = zod.object({
  "vehicleId": zod.string(),
  "recordId": zod.string()
})

export const getMaintenanceRecordResponseMileageMin = 0;



export const GetMaintenanceRecordResponse = zod.object({
  "id": zod.string().optional(),
  "cost": zod.string().optional().describe('Cost of the service.'),
  "date": zod.iso.date(),
  "description": zod.string(),
  "mileage": zod.number().min(getMaintenanceRecordResponseMileageMin),
  "notes": zod.string().optional().describe('Optional notes.')
})


/**
 * @summary Update an existing maintenance record
 */
export const UpdateMaintenanceRecordParams = zod.object({
  "vehicleId": zod.string(),
  "recordId": zod.string()
})

export const updateMaintenanceRecordBodyMileageMin = 0;



export const UpdateMaintenanceRecordBody = zod.object({
  "cost": zod.string().optional().describe('Cost of the service.'),
  "date": zod.iso.date(),
  "description": zod.string(),
  "mileage": zod.number().min(updateMaintenanceRecordBodyMileageMin),
  "notes": zod.string().optional().describe('Optional notes.')
})


/**
 * @summary Delete a maintenance record
 */
export const DeleteMaintenanceRecordParams = zod.object({
  "vehicleId": zod.string(),
  "recordId": zod.string()
})
