/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Service Tracker API
 * An API to track vehicle maintenance records.
 * OpenAPI spec version: 0.0.1
 */

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> = (<T>() => T extends X ? 1 : 2) extends <
T,
>() => T extends Y ? 1 : 2
? A
: B;

type WritableKeys<T> = {
[P in keyof T]-?: IfEquals<
  { [Q in P]: T[P] },
  { -readonly [Q in P]: T[P] },
  P
>;
}[keyof T];

type UnionToIntersection<U> =
  (U extends any ? (k: U)=>void : never) extends ((k: infer I)=>void) ? I : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>] ? {
  [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P];
} : DistributeReadOnlyOverUnions<T>;

export interface MaintenanceRecord {
  readonly id?: string;
  /** Cost of the service. */
  cost?: string;
  date: string;
  description: string;
  /** @minimum 0 */
  mileage: number;
  /** Optional notes. */
  notes?: string;
}

export interface Vehicle {
  readonly id?: string;
  make: string;
  model: string;
  /**
   * @minimum 1900
   * @maximum 2025
   */
  year: number;
}

/**
 * @summary Retrieve a list of vehicles
 */
export type getVehiclesResponse200 = {
  data: Vehicle[]
  status: 200
}
    
export type getVehiclesResponseSuccess = (getVehiclesResponse200) & {
  headers: Headers;
};
;

export type getVehiclesResponse = (getVehiclesResponseSuccess)

export const getGetVehiclesUrl = () => {


  

  return `/api/vehicles`
}

export const getVehicles = async ( options?: RequestInit): Promise<getVehiclesResponse> => {
  
  const res = await fetch(getGetVehiclesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getVehiclesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getVehiclesResponse
}



/**
 * @summary Add a new vehicle
 */
export type postVehiclesResponse201 = {
  data: void
  status: 201
}
    
export type postVehiclesResponseSuccess = (postVehiclesResponse201) & {
  headers: Headers;
};
;

export type postVehiclesResponse = (postVehiclesResponseSuccess)

export const getPostVehiclesUrl = () => {


  

  return `/api/vehicles`
}

export const postVehicles = async (vehicle: NonReadonly<Vehicle>, options?: RequestInit): Promise<postVehiclesResponse> => {
  
  const res = await fetch(getPostVehiclesUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      vehicle,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postVehiclesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postVehiclesResponse
}
