/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddVehicleRouteImport } from './routes/add-vehicle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VehicleDetailsVehicleIdRouteImport } from './routes/vehicle-details.$vehicleId'
import { Route as EditVehicleVehicleIdRouteImport } from './routes/edit-vehicle.$vehicleId'

const AddVehicleRoute = AddVehicleRouteImport.update({
  id: '/add-vehicle',
  path: '/add-vehicle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleDetailsVehicleIdRoute = VehicleDetailsVehicleIdRouteImport.update({
  id: '/vehicle-details/$vehicleId',
  path: '/vehicle-details/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditVehicleVehicleIdRoute = EditVehicleVehicleIdRouteImport.update({
  id: '/edit-vehicle/$vehicleId',
  path: '/edit-vehicle/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/edit-vehicle/$vehicleId': typeof EditVehicleVehicleIdRoute
  '/vehicle-details/$vehicleId': typeof VehicleDetailsVehicleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/edit-vehicle/$vehicleId': typeof EditVehicleVehicleIdRoute
  '/vehicle-details/$vehicleId': typeof VehicleDetailsVehicleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-vehicle': typeof AddVehicleRoute
  '/edit-vehicle/$vehicleId': typeof EditVehicleVehicleIdRoute
  '/vehicle-details/$vehicleId': typeof VehicleDetailsVehicleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-vehicle'
    | '/edit-vehicle/$vehicleId'
    | '/vehicle-details/$vehicleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-vehicle'
    | '/edit-vehicle/$vehicleId'
    | '/vehicle-details/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/add-vehicle'
    | '/edit-vehicle/$vehicleId'
    | '/vehicle-details/$vehicleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddVehicleRoute: typeof AddVehicleRoute
  EditVehicleVehicleIdRoute: typeof EditVehicleVehicleIdRoute
  VehicleDetailsVehicleIdRoute: typeof VehicleDetailsVehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add-vehicle': {
      id: '/add-vehicle'
      path: '/add-vehicle'
      fullPath: '/add-vehicle'
      preLoaderRoute: typeof AddVehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-details/$vehicleId': {
      id: '/vehicle-details/$vehicleId'
      path: '/vehicle-details/$vehicleId'
      fullPath: '/vehicle-details/$vehicleId'
      preLoaderRoute: typeof VehicleDetailsVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-vehicle/$vehicleId': {
      id: '/edit-vehicle/$vehicleId'
      path: '/edit-vehicle/$vehicleId'
      fullPath: '/edit-vehicle/$vehicleId'
      preLoaderRoute: typeof EditVehicleVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddVehicleRoute: AddVehicleRoute,
  EditVehicleVehicleIdRoute: EditVehicleVehicleIdRoute,
  VehicleDetailsVehicleIdRoute: VehicleDetailsVehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
