// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Vehicle defines model for Vehicle.
type Vehicle struct {
	Id    *string `json:"id,omitempty"`
	Make  string  `json:"make"`
	Model string  `json:"model"`
	Year  int     `json:"year"`
}

// PostVehiclesJSONRequestBody defines body for PostVehicles for application/json ContentType.
type PostVehiclesJSONRequestBody = Vehicle

// PutVehiclesVehicleIdJSONRequestBody defines body for PutVehiclesVehicleId for application/json ContentType.
type PutVehiclesVehicleIdJSONRequestBody = Vehicle

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve a list of vehicles
	// (GET /vehicles)
	GetVehicles(w http.ResponseWriter, r *http.Request)
	// Add a new vehicle
	// (POST /vehicles)
	PostVehicles(w http.ResponseWriter, r *http.Request)
	// Delete a vehicle
	// (DELETE /vehicles/{vehicleId})
	DeleteVehiclesVehicleId(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Retrieve a vehicle by ID
	// (GET /vehicles/{vehicleId})
	GetVehiclesVehicleId(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Update an existing vehicle
	// (PUT /vehicles/{vehicleId})
	PutVehiclesVehicleId(w http.ResponseWriter, r *http.Request, vehicleId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Retrieve a list of vehicles
// (GET /vehicles)
func (_ Unimplemented) GetVehicles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new vehicle
// (POST /vehicles)
func (_ Unimplemented) PostVehicles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a vehicle
// (DELETE /vehicles/{vehicleId})
func (_ Unimplemented) DeleteVehiclesVehicleId(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve a vehicle by ID
// (GET /vehicles/{vehicleId})
func (_ Unimplemented) GetVehiclesVehicleId(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing vehicle
// (PUT /vehicles/{vehicleId})
func (_ Unimplemented) PutVehiclesVehicleId(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetVehicles operation middleware
func (siw *ServerInterfaceWrapper) GetVehicles(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVehicles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVehicles operation middleware
func (siw *ServerInterfaceWrapper) PostVehicles(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVehicles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVehiclesVehicleId operation middleware
func (siw *ServerInterfaceWrapper) DeleteVehiclesVehicleId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVehiclesVehicleId(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVehiclesVehicleId operation middleware
func (siw *ServerInterfaceWrapper) GetVehiclesVehicleId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVehiclesVehicleId(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutVehiclesVehicleId operation middleware
func (siw *ServerInterfaceWrapper) PutVehiclesVehicleId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutVehiclesVehicleId(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles", wrapper.GetVehicles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vehicles", wrapper.PostVehicles)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vehicles/{vehicleId}", wrapper.DeleteVehiclesVehicleId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}", wrapper.GetVehiclesVehicleId)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/vehicles/{vehicleId}", wrapper.PutVehiclesVehicleId)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8RVz2/bOgz+VwS+dzRit68P6PMtD8WGDBtarF12KHJQZSZRa0sqRWc1Av/vg+Q4v9N2",
	"h2GX2ArFj+THj/QSlK2cNWjYQ74Er+ZYyfg6xrlWJYZXR9YhscZo0EX4JZTFtSkbyJlqTIAbh5CDZ9Jm",
	"Bm0ClXyKzocGW2B51NKgpGCo5Iuu6gry8+z83wQqbbrj2X9Zto6kDeMMCdo2AcLnWhMWkN93cfsoK8zJ",
	"2ss+PKLi6ORR1aS5uQ01d6U9oCSkYc3zzemDpUoy5PDp+x0kHUMBqbPCGnnO7KANwNpMbfAv0CvSjrU1",
	"kMPQiOHNSLAVTFI9iUXHr6hkqMRIo1AQKkuFHwRUzYF8uEVaaIXiLjghBQxIYIHkO9hskA3OAnnWoZFO",
	"Qw7/DLJBBgk4yfNYVrqKFQ8z5PAIHZUhtVEBOXxEHvd3Ap3eWeO7++dZFh7Khiyjq3Su1Co6p48+ZNEL",
	"J8qDsYqOfxNOIYe/0o3E0pW+0l5c7Zo+SSSbjr893kSpPQs7FesqYvfqqpLUQA5fkUnjAoU8cjMBZ/2R",
	"gm+s3634uUbP/9ui+aVi31XjrkLDuLQHHJ8dCmblLxShZCyEr5VC76d1WTZ7FAyLQkhh8EdfebSv254u",
	"V2+jou3ilMh4SMpV/L+nZdz7HCri4nS2Hfar2XZhhNwkm7ypyleSyX5Px/ZV2M9rv0ESuHiNB2NZTG1t",
	"itNq7REfGjG6ilKVJCtkJA/5/RJ0wAtDDAkYGZfOYoeGbUklWzXuLdZ2koCrjw1BfYLfPzwM2Wlaa1e8",
	"NQzf4hUhjcAX7Vmb2dZUbO39yPH2xr+fBKY80qLvwG4On62SpShwgaV1FRoW3V1IoKZy9QnI07QM9+bW",
	"c36ZXWYQQFnOjiFe9+3wgrCMhbHdbK9128ebffY+iCMflQ3al40R2kn7MwAA//9KYNGZBAgAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
