// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Vehicle struct {
	ID        pgtype.UUID        `json:"id"`
	Make      string             `json:"make"`
	Model     string             `json:"model"`
	Year      int32              `json:"year"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
