// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (make, model, year)
VALUES ($1, $2, $3)
RETURNING id, make, model, year, created_at
`

type CreateVehicleParams struct {
	Make  string `json:"make"`
	Model string `json:"model"`
	Year  int32  `json:"year"`
}

func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle, arg.Make, arg.Model, arg.Year)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
DELETE FROM vehicles
WHERE id = $1
`

func (q *Queries) DeleteVehicle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVehicle, id)
	return err
}

const getVehicle = `-- name: GetVehicle :one
SELECT id, make, model, year, created_at FROM vehicles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVehicle(ctx context.Context, id pgtype.UUID) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}

const listVehicles = `-- name: ListVehicles :many
SELECT id, make, model, year, created_at FROM vehicles
ORDER BY created_at DESC
`

func (q *Queries) ListVehicles(ctx context.Context) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vehicle
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.ID,
			&i.Make,
			&i.Model,
			&i.Year,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET make = $2, model = $3, year = $4
WHERE id = $1
RETURNING id, make, model, year, created_at
`

type UpdateVehicleParams struct {
	ID    pgtype.UUID `json:"id"`
	Make  string      `json:"make"`
	Model string      `json:"model"`
	Year  int32       `json:"year"`
}

func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.ID,
		arg.Make,
		arg.Model,
		arg.Year,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.Make,
		&i.Model,
		&i.Year,
		&i.CreatedAt,
	)
	return i, err
}
