// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// MaintenanceRecord defines model for MaintenanceRecord.
type MaintenanceRecord struct {
	// Cost Cost of the service.
	Cost        *string            `json:"cost,omitempty"`
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
	Id          *string            `json:"id,omitempty"`
	Mileage     int                `json:"mileage"`

	// Notes Optional notes.
	Notes *string `json:"notes,omitempty"`
}

// Vehicle defines model for Vehicle.
type Vehicle struct {
	Id    *string `json:"id,omitempty"`
	Make  string  `json:"make"`
	Model string  `json:"model"`
	Year  int     `json:"year"`
}

// VehicleImage defines model for VehicleImage.
type VehicleImage struct {
	Filename string `json:"filename"`
	Id       *int   `json:"id,omitempty"`
}

// CreateVehicleJSONRequestBody defines body for CreateVehicle for application/json ContentType.
type CreateVehicleJSONRequestBody = Vehicle

// UpdateVehicleJSONRequestBody defines body for UpdateVehicle for application/json ContentType.
type UpdateVehicleJSONRequestBody = Vehicle

// CreateMaintenanceRecordJSONRequestBody defines body for CreateMaintenanceRecord for application/json ContentType.
type CreateMaintenanceRecordJSONRequestBody = MaintenanceRecord

// UpdateMaintenanceRecordJSONRequestBody defines body for UpdateMaintenanceRecord for application/json ContentType.
type UpdateMaintenanceRecordJSONRequestBody = MaintenanceRecord

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve a list of vehicles
	// (GET /vehicles)
	ListVehicles(w http.ResponseWriter, r *http.Request)
	// Add a new vehicle
	// (POST /vehicles)
	CreateVehicle(w http.ResponseWriter, r *http.Request)
	// Delete a vehicle
	// (DELETE /vehicles/{vehicleId})
	DeleteVehicle(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Retrieve a vehicle by ID
	// (GET /vehicles/{vehicleId})
	GetVehicle(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Update an existing vehicle
	// (PUT /vehicles/{vehicleId})
	UpdateVehicle(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Retrieve images for a vehicle
	// (GET /vehicles/{vehicleId}/images)
	GetVehicleImages(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Retrieve maintenance records for a vehicle
	// (GET /vehicles/{vehicleId}/maintenance)
	ListMaintenanceRecords(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Add a maintenance record for a vehicle
	// (POST /vehicles/{vehicleId}/maintenance)
	CreateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Delete a maintenance record
	// (DELETE /vehicles/{vehicleId}/maintenance/{recordId})
	DeleteMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string)
	// Retrieve a specific maintenance record
	// (GET /vehicles/{vehicleId}/maintenance/{recordId})
	GetMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string)
	// Update an existing maintenance record
	// (PUT /vehicles/{vehicleId}/maintenance/{recordId})
	UpdateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Retrieve a list of vehicles
// (GET /vehicles)
func (_ Unimplemented) ListVehicles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new vehicle
// (POST /vehicles)
func (_ Unimplemented) CreateVehicle(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a vehicle
// (DELETE /vehicles/{vehicleId})
func (_ Unimplemented) DeleteVehicle(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve a vehicle by ID
// (GET /vehicles/{vehicleId})
func (_ Unimplemented) GetVehicle(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing vehicle
// (PUT /vehicles/{vehicleId})
func (_ Unimplemented) UpdateVehicle(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve images for a vehicle
// (GET /vehicles/{vehicleId}/images)
func (_ Unimplemented) GetVehicleImages(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve maintenance records for a vehicle
// (GET /vehicles/{vehicleId}/maintenance)
func (_ Unimplemented) ListMaintenanceRecords(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a maintenance record for a vehicle
// (POST /vehicles/{vehicleId}/maintenance)
func (_ Unimplemented) CreateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a maintenance record
// (DELETE /vehicles/{vehicleId}/maintenance/{recordId})
func (_ Unimplemented) DeleteMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve a specific maintenance record
// (GET /vehicles/{vehicleId}/maintenance/{recordId})
func (_ Unimplemented) GetMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing maintenance record
// (PUT /vehicles/{vehicleId}/maintenance/{recordId})
func (_ Unimplemented) UpdateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListVehicles operation middleware
func (siw *ServerInterfaceWrapper) ListVehicles(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVehicles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVehicle operation middleware
func (siw *ServerInterfaceWrapper) CreateVehicle(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVehicle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVehicle operation middleware
func (siw *ServerInterfaceWrapper) DeleteVehicle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVehicle(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVehicle operation middleware
func (siw *ServerInterfaceWrapper) GetVehicle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVehicle(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateVehicle operation middleware
func (siw *ServerInterfaceWrapper) UpdateVehicle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateVehicle(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVehicleImages operation middleware
func (siw *ServerInterfaceWrapper) GetVehicleImages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVehicleImages(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMaintenanceRecords operation middleware
func (siw *ServerInterfaceWrapper) ListMaintenanceRecords(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMaintenanceRecords(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) CreateMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMaintenanceRecord(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) DeleteMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", chi.URLParam(r, "recordId"), &recordId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMaintenanceRecord(w, r, vehicleId, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) GetMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", chi.URLParam(r, "recordId"), &recordId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMaintenanceRecord(w, r, vehicleId, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) UpdateMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", chi.URLParam(r, "recordId"), &recordId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMaintenanceRecord(w, r, vehicleId, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles", wrapper.ListVehicles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vehicles", wrapper.CreateVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vehicles/{vehicleId}", wrapper.DeleteVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}", wrapper.GetVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/vehicles/{vehicleId}", wrapper.UpdateVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}/images", wrapper.GetVehicleImages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}/maintenance", wrapper.ListMaintenanceRecords)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vehicles/{vehicleId}/maintenance", wrapper.CreateMaintenanceRecord)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vehicles/{vehicleId}/maintenance/{recordId}", wrapper.DeleteMaintenanceRecord)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}/maintenance/{recordId}", wrapper.GetMaintenanceRecord)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/vehicles/{vehicleId}/maintenance/{recordId}", wrapper.UpdateMaintenanceRecord)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RX32/bNhD+V4jbHgVLyYqh05vXYoOHFBnSNnsI8sBQZ5utRGok5dUw/L8PJPXTohy7",
	"qIv0ybJ4PN5933d34g6YLEopUBgN6Q40W2NB3eM7yoVBQQXDO2RSZfZlqWSJynB0JkxqY38z1Ezx0nAp",
	"IIU3Uhsil8SskWhUG85wBhGYbYmQgjaKixXsI8ioQbt7KVVBDaT+Rciw7343XucuNIU0uxX5FlKjKgy4",
	"KXiOdOWOLLjgRVVAmrR2NtkVKmsopPH5DfO6dQ80J249kNI+AoX/VlxhBulDk07fSRfEY7tbPn1CZuy5",
	"97jmLMcxzqcmSD9jEKBCZpgHV7ZIlQOEfvGAXCfXv0YdPle/JQGIDhLlGdSHN0fVjo8kuShqKoaZLnmO",
	"ghZ4Ps9TwbUex8HsI9DIKsXN9r3VvQ/hCalCNa/Muvv3RyPRv/75AJGvEuvJr3ZKWBtTwt465mIpxxKa",
	"CzL/e0GMJEZR9plsPBik6GqNKFdsXl/cWDnAe19F5IPdhMr6gAg2qLR3m8yS2ZVFSJYoaMkhhV9mySyB",
	"CEpq1i6tuD7L/Vmhq1uLPLWhLTJI4YZrc98YWRB1KYX2G66TxBe8DdPtpWWZc+Z2x5+0r0zfPZxiDRZu",
	"488Kl5DCT3HXZ+K6ycSN3vctflQpuvUAHgBHcu67SpuGo68qCqq2kMIdGsVxg4QGLCMo6041zPiNQmqw",
	"CcPrBrX5XWbbs7I9KcmhMK129yOQry5z7BDLeokwl31GdMUYar2s8nx7gOo8ywglAv9rwHTrrZTiXf20",
	"yPZe7Dn6nj7E+a1738d5kPWrcaE0MXqPR2P0zgntQozC+v4TzWQIyfcAft7We9cOXx3LXkhDlrIS2bTY",
	"G49PW7J465ROFS3QoNKQPuyAW3+2CUAEvrFCyxkcCjLq5Xg42x4jKKsAqh/L7GXVUDKNZ+ViPaomnw6h",
	"guAXrg0Xq+elH3M7zKYbaye8hTe8KEvfrW/7EX5W83ZAkY93N5Pt20NJllL1K3oS+d7gPDrXRh+zPzwJ",
	"48/zs5gIfHFMURIwPeTn+IAdh3ph7L99BwqgffI8H1LwboTm6YN4zMTXFEq883tPGtoh7p4f3970rOk9",
	"zu3YID8hrOTS5B+WVoCdZ+Z8DdMJY16XyPiSswmYLlVNUdBXI59v+P0Q5vPF1HEyyd3XfVKEWOxfRx2L",
	"/Yvow6MFUKPaNBwPo7mRjOYkww3msixQGOJtIYJK5fXNNI3j3NqtpTbp6+R1AtapoauQx9uGJU0U5i5H",
	"I7s7VSuG++6WdZqL0ORpvfX4gf3j/v8AAAD//1kxgmyfEgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
