// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// MaintenanceRecord defines model for MaintenanceRecord.
type MaintenanceRecord struct {
	// Cost Cost of the service.
	Cost        *string            `json:"cost,omitempty"`
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
	Id          *string            `json:"id,omitempty"`
	Mileage     int                `json:"mileage"`

	// Notes Optional notes.
	Notes *string `json:"notes,omitempty"`
}

// Vehicle defines model for Vehicle.
type Vehicle struct {
	Id    *string `json:"id,omitempty"`
	Make  string  `json:"make"`
	Model string  `json:"model"`
	Year  int     `json:"year"`
}

// CreateVehicleJSONRequestBody defines body for CreateVehicle for application/json ContentType.
type CreateVehicleJSONRequestBody = Vehicle

// UpdateVehicleJSONRequestBody defines body for UpdateVehicle for application/json ContentType.
type UpdateVehicleJSONRequestBody = Vehicle

// CreateMaintenanceRecordJSONRequestBody defines body for CreateMaintenanceRecord for application/json ContentType.
type CreateMaintenanceRecordJSONRequestBody = MaintenanceRecord

// UpdateMaintenanceRecordJSONRequestBody defines body for UpdateMaintenanceRecord for application/json ContentType.
type UpdateMaintenanceRecordJSONRequestBody = MaintenanceRecord

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve a list of vehicles
	// (GET /vehicles)
	ListVehicles(w http.ResponseWriter, r *http.Request)
	// Add a new vehicle
	// (POST /vehicles)
	CreateVehicle(w http.ResponseWriter, r *http.Request)
	// Delete a vehicle
	// (DELETE /vehicles/{vehicleId})
	DeleteVehicle(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Retrieve a vehicle by ID
	// (GET /vehicles/{vehicleId})
	GetVehicle(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Update an existing vehicle
	// (PUT /vehicles/{vehicleId})
	UpdateVehicle(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Retrieve maintenance records for a vehicle
	// (GET /vehicles/{vehicleId}/maintenance)
	ListMaintenanceRecords(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Add a maintenance record for a vehicle
	// (POST /vehicles/{vehicleId}/maintenance)
	CreateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Delete a maintenance record
	// (DELETE /vehicles/{vehicleId}/maintenance/{recordId})
	DeleteMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string)
	// Retrieve a specific maintenance record
	// (GET /vehicles/{vehicleId}/maintenance/{recordId})
	GetMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string)
	// Update an existing maintenance record
	// (PUT /vehicles/{vehicleId}/maintenance/{recordId})
	UpdateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Retrieve a list of vehicles
// (GET /vehicles)
func (_ Unimplemented) ListVehicles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new vehicle
// (POST /vehicles)
func (_ Unimplemented) CreateVehicle(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a vehicle
// (DELETE /vehicles/{vehicleId})
func (_ Unimplemented) DeleteVehicle(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve a vehicle by ID
// (GET /vehicles/{vehicleId})
func (_ Unimplemented) GetVehicle(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing vehicle
// (PUT /vehicles/{vehicleId})
func (_ Unimplemented) UpdateVehicle(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve maintenance records for a vehicle
// (GET /vehicles/{vehicleId}/maintenance)
func (_ Unimplemented) ListMaintenanceRecords(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a maintenance record for a vehicle
// (POST /vehicles/{vehicleId}/maintenance)
func (_ Unimplemented) CreateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a maintenance record
// (DELETE /vehicles/{vehicleId}/maintenance/{recordId})
func (_ Unimplemented) DeleteMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve a specific maintenance record
// (GET /vehicles/{vehicleId}/maintenance/{recordId})
func (_ Unimplemented) GetMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing maintenance record
// (PUT /vehicles/{vehicleId}/maintenance/{recordId})
func (_ Unimplemented) UpdateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListVehicles operation middleware
func (siw *ServerInterfaceWrapper) ListVehicles(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVehicles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVehicle operation middleware
func (siw *ServerInterfaceWrapper) CreateVehicle(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVehicle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVehicle operation middleware
func (siw *ServerInterfaceWrapper) DeleteVehicle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVehicle(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVehicle operation middleware
func (siw *ServerInterfaceWrapper) GetVehicle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVehicle(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateVehicle operation middleware
func (siw *ServerInterfaceWrapper) UpdateVehicle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateVehicle(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMaintenanceRecords operation middleware
func (siw *ServerInterfaceWrapper) ListMaintenanceRecords(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMaintenanceRecords(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) CreateMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMaintenanceRecord(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) DeleteMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", chi.URLParam(r, "recordId"), &recordId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMaintenanceRecord(w, r, vehicleId, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) GetMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", chi.URLParam(r, "recordId"), &recordId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMaintenanceRecord(w, r, vehicleId, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) UpdateMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", chi.URLParam(r, "recordId"), &recordId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMaintenanceRecord(w, r, vehicleId, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles", wrapper.ListVehicles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vehicles", wrapper.CreateVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vehicles/{vehicleId}", wrapper.DeleteVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}", wrapper.GetVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/vehicles/{vehicleId}", wrapper.UpdateVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}/maintenance", wrapper.ListMaintenanceRecords)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vehicles/{vehicleId}/maintenance", wrapper.CreateMaintenanceRecord)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vehicles/{vehicleId}/maintenance/{recordId}", wrapper.DeleteMaintenanceRecord)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}/maintenance/{recordId}", wrapper.GetMaintenanceRecord)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/vehicles/{vehicleId}/maintenance/{recordId}", wrapper.UpdateMaintenanceRecord)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX32/bthP/V4j7fh8FS8k6oNNb1mJDhhYZ2i57CPLAUGebrURy5MmrYOh/H0halm3R",
	"jlPUQJ8sS+TxPj/uTlqD0I3RChU5KNfgxBIbHi7fc6kIFVcCP6DQtvI3jdUGLUkMS4R25H8rdMJKQ1Ir",
	"KOGNdsT0nNESmUO7kgJnkAF1BqEER1aqBfQZVJzQ755r23CCMt5ILdwNv54+lyE1i7y6U3UHJdkWE2Ea",
	"WSNfhCMbqWTTNlAW23Ue7AKtX6g0RXz7uO7CBa9ZeJ6A1Gdg8Z9WWqygfBjg7AYZk3jc7tZPn1GQP/ce",
	"l1LUOOX5XID8CyYJanSFdfJJh9wGQvjXSMh1cf1zNvJz9UuRoOgAaDh3OGUTc4qvz8ChaK2k7qN3WYT2",
	"hNyivWlpOf77bTDEH39/gix60keKT0fel0QGeh9YqrmeCnaj2M2ft4w0I8vFF7aK/LJmdDazwdpRTUme",
	"fPgYPcs++U1ofQzIYIXWxbDFrJhdefK0QcWNhBJ+mhWzAjIwnJYBVr45K/xZYKgSryj3qd1WUMI76eh+",
	"WOT5dEYrFzdcF0UsL59m2MuNqaUIu/PPLtZBrNXgD8ImbPy/xTmU8L98rOp8U9L54K5+yx+3lneRwAPi",
	"WC1jDW9hBPnapuG2gxI+IFmJK2Q8sTIDs+kL+4jfWOSEQxrRQujoV111L0J7Fsh9j/qC6SckX00ts9nP",
	"RMi1Yq4VAp2bt3XdHXBwU1WMM4X/DtDD863w+XpzdVv18ZwaY7/bZ+VtuL/Lyl6Or47nGCOezDEGZ3xM",
	"MUu78XekoykUl1Hn0HJDdY798NUp9EoTm+tWVcetOUR86tjt2+BLbnmDhNZB+bAG6eP5koUMFA8tZqsZ",
	"HNon28F42PcfMzBtgtW/TPVjOb44zmcbcj3ppgiHccXwq3Qk1eJ56+c7zfZkL5y8bji4qGCXb7jTF6gX",
	"td7ElDpm9cRSNtd2v+5PNeVpqhfm/vvXQYLtb5wB7ydsnj8OpkocCnFOoeTruPes0ZHS7vkhEpe+aIZM",
	"sZ0aJ2ekVVxa/MPSSqjzzLTZ0HTGsHEGhZxLcYSmS1VTlow12Oc7TrG0nj9MHRdHtfu2wZZScfcTJqi4",
	"+/Hy8OgJ9N+7g8b72bzTgteswhXW2jSoiMW1kEFr683XTJnntV+31I7K18XrAnxQ4otUxLtBJccs1gEj",
	"6fE9fGuG+/HN/LwQqcmzjbajD/SP/X8BAAD//wceQRJBEAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
