// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// MaintenanceRecord defines model for MaintenanceRecord.
type MaintenanceRecord struct {
	// Cost Cost of the service.
	Cost        *string            `json:"cost,omitempty"`
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
	Id          *string            `json:"id,omitempty"`
	Mileage     int                `json:"mileage"`

	// Notes Optional notes.
	Notes *string `json:"notes,omitempty"`
}

// Vehicle defines model for Vehicle.
type Vehicle struct {
	Id    *string `json:"id,omitempty"`
	Make  string  `json:"make"`
	Model string  `json:"model"`
	Year  int     `json:"year"`
}

// VehicleImage defines model for VehicleImage.
type VehicleImage struct {
	Filename string `json:"filename"`
	Id       *int   `json:"id,omitempty"`
}

// CreateVehicleJSONRequestBody defines body for CreateVehicle for application/json ContentType.
type CreateVehicleJSONRequestBody = Vehicle

// UpdateVehicleJSONRequestBody defines body for UpdateVehicle for application/json ContentType.
type UpdateVehicleJSONRequestBody = Vehicle

// CreateMaintenanceRecordJSONRequestBody defines body for CreateMaintenanceRecord for application/json ContentType.
type CreateMaintenanceRecordJSONRequestBody = MaintenanceRecord

// UpdateMaintenanceRecordJSONRequestBody defines body for UpdateMaintenanceRecord for application/json ContentType.
type UpdateMaintenanceRecordJSONRequestBody = MaintenanceRecord

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve a list of vehicles
	// (GET /vehicles)
	ListVehicles(w http.ResponseWriter, r *http.Request)
	// Add a new vehicle
	// (POST /vehicles)
	CreateVehicle(w http.ResponseWriter, r *http.Request)
	// Delete a vehicle
	// (DELETE /vehicles/{vehicleId})
	DeleteVehicle(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Retrieve a vehicle by ID
	// (GET /vehicles/{vehicleId})
	GetVehicle(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Update an existing vehicle
	// (PUT /vehicles/{vehicleId})
	UpdateVehicle(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Retrieve images for a vehicle
	// (GET /vehicles/{vehicleId}/images)
	GetVehicleImages(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Retrieve maintenance records for a vehicle
	// (GET /vehicles/{vehicleId}/maintenance)
	ListMaintenanceRecords(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Add a maintenance record for a vehicle
	// (POST /vehicles/{vehicleId}/maintenance)
	CreateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string)
	// Delete a maintenance record
	// (DELETE /vehicles/{vehicleId}/maintenance/{recordId})
	DeleteMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string)
	// Retrieve a specific maintenance record
	// (GET /vehicles/{vehicleId}/maintenance/{recordId})
	GetMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string)
	// Update an existing maintenance record
	// (PUT /vehicles/{vehicleId}/maintenance/{recordId})
	UpdateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Retrieve a list of vehicles
// (GET /vehicles)
func (_ Unimplemented) ListVehicles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new vehicle
// (POST /vehicles)
func (_ Unimplemented) CreateVehicle(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a vehicle
// (DELETE /vehicles/{vehicleId})
func (_ Unimplemented) DeleteVehicle(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve a vehicle by ID
// (GET /vehicles/{vehicleId})
func (_ Unimplemented) GetVehicle(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing vehicle
// (PUT /vehicles/{vehicleId})
func (_ Unimplemented) UpdateVehicle(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve images for a vehicle
// (GET /vehicles/{vehicleId}/images)
func (_ Unimplemented) GetVehicleImages(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve maintenance records for a vehicle
// (GET /vehicles/{vehicleId}/maintenance)
func (_ Unimplemented) ListMaintenanceRecords(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a maintenance record for a vehicle
// (POST /vehicles/{vehicleId}/maintenance)
func (_ Unimplemented) CreateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a maintenance record
// (DELETE /vehicles/{vehicleId}/maintenance/{recordId})
func (_ Unimplemented) DeleteMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Retrieve a specific maintenance record
// (GET /vehicles/{vehicleId}/maintenance/{recordId})
func (_ Unimplemented) GetMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update an existing maintenance record
// (PUT /vehicles/{vehicleId}/maintenance/{recordId})
func (_ Unimplemented) UpdateMaintenanceRecord(w http.ResponseWriter, r *http.Request, vehicleId string, recordId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListVehicles operation middleware
func (siw *ServerInterfaceWrapper) ListVehicles(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListVehicles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateVehicle operation middleware
func (siw *ServerInterfaceWrapper) CreateVehicle(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateVehicle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteVehicle operation middleware
func (siw *ServerInterfaceWrapper) DeleteVehicle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteVehicle(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVehicle operation middleware
func (siw *ServerInterfaceWrapper) GetVehicle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVehicle(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateVehicle operation middleware
func (siw *ServerInterfaceWrapper) UpdateVehicle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateVehicle(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVehicleImages operation middleware
func (siw *ServerInterfaceWrapper) GetVehicleImages(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVehicleImages(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMaintenanceRecords operation middleware
func (siw *ServerInterfaceWrapper) ListMaintenanceRecords(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMaintenanceRecords(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) CreateMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMaintenanceRecord(w, r, vehicleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) DeleteMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", chi.URLParam(r, "recordId"), &recordId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMaintenanceRecord(w, r, vehicleId, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) GetMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", chi.URLParam(r, "recordId"), &recordId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMaintenanceRecord(w, r, vehicleId, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMaintenanceRecord operation middleware
func (siw *ServerInterfaceWrapper) UpdateMaintenanceRecord(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "vehicleId" -------------
	var vehicleId string

	err = runtime.BindStyledParameterWithOptions("simple", "vehicleId", chi.URLParam(r, "vehicleId"), &vehicleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "vehicleId", Err: err})
		return
	}

	// ------------- Path parameter "recordId" -------------
	var recordId string

	err = runtime.BindStyledParameterWithOptions("simple", "recordId", chi.URLParam(r, "recordId"), &recordId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recordId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMaintenanceRecord(w, r, vehicleId, recordId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles", wrapper.ListVehicles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vehicles", wrapper.CreateVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vehicles/{vehicleId}", wrapper.DeleteVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}", wrapper.GetVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/vehicles/{vehicleId}", wrapper.UpdateVehicle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}/images", wrapper.GetVehicleImages)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}/maintenance", wrapper.ListMaintenanceRecords)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/vehicles/{vehicleId}/maintenance", wrapper.CreateMaintenanceRecord)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/vehicles/{vehicleId}/maintenance/{recordId}", wrapper.DeleteMaintenanceRecord)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/vehicles/{vehicleId}/maintenance/{recordId}", wrapper.GetMaintenanceRecord)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/vehicles/{vehicleId}/maintenance/{recordId}", wrapper.UpdateMaintenanceRecord)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RX32/bNhD+V4jbHgVLzTqg01vWYoOHFBnSNnsI8sBQZ5utRGok5VUw9L8PJPXLFuXY",
	"QT10T5al4/Hu+767I3fAZFFKgcJoSHeg2QYL6h7fUy4MCioY3iGTKrMvSyVLVIajM2FSG/uboWaKl4ZL",
	"ASm8ldoQuSJmg0Sj2nKGC4jA1CVCCtooLtbQRJBRg3b1SqqCGkj9i5Dh2P1u+p270BTS7FbkNaRGVRhw",
	"U/Ac6dptWXDBi6qANOntbLJrVNZQSOPz28/r1j3QnLjvgZSaCBT+XXGFGaQPXTpjJ0MQj/1q+fQZmbH7",
	"3uOGsxynOJ+aIP2CQYAKmWEe/FIjVQ4Q+tUDcpVc/RwN+Lz6JQlAdJCo27fbpfV5JL9l0bKwn+SK5yho",
	"gedTPBdX73EaTBOBRlYpbuoPVvI+hCekCtV1ZTbDv986df7x10eIfIFYT/7rIIKNMSU01jEXKzlVz7Ug",
	"138uiZHEKMq+kK0HgxRDmRHl6sxLixurBPjgC4h8tItQWR8QwRaV9m6TRbJ4ZRGSJQpackjhp0WySCCC",
	"kpqNSytu93J/1uhK1iJPbWjLDFK44drcd0YWRF1Kof2CqyTxtW7DdGtpWeacudXxZ+2L0jcOJ1aDhVv4",
	"o8IVpPBDPLSYuO0vcSf1psePKkVrD+ABcCTnvqH0aTj6qqKgqoYU7tAojlskNGAZQdk2qf2M3yqkBrsw",
	"vG5Qm19lVp+V7UlJ7gvTareZgPxqKpl2PWEu1ozoijHUelXleX2AwXWWEUoE/tOl7r73xMe79mmZNX6f",
	"HH3z3UflnXs/RmUvxtfzMXqPR2P0zgkdQozCavwdzWwIyWXYOZRcV51D83p9LHshDVnJSmTz0uw8PtVk",
	"+c7pkipaoEGlIX3YAbf+bMlCBL4NQs8ZHMonGuV4OIQeIyirAKqfyuz7Unwyj2flYj2qJp8OoYLgV64N",
	"F+vnpR9zO3rm2+AgvKU3vChL/1mX9QP3rFbrgCKf7m5mm62HkqykGlf0LPKjMXd0Ck1Onf97Eqbn6LOY",
	"CJwP5igJmB7yc3wcTkO9MPbfvgMF0H7h9H0/QfP0QTxl4iWFEu/82pOGdoi758e3Nz1rek9zOzbITwgr",
	"uTT5h6UVYOeZOd/CdMKY1yUyvuJsBqZLVVMU9NXJ5xueH8J8fjd1nMxy97IjRYjF8eXRsTi+Nj48WgA1",
	"qm3H8X40N5LRnGS4xVyWBQpDvC1EUKm8vUemcZxbu43UJn2TvEnAOjV0HfJ427GkicLc5WjkcAPqxXA/",
	"3IlOcxGaPL23ET/QPDb/BgAA///C10YLSBIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
